apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: k8scomplex
spec:
  selector:
    k8scomplex-service: stage
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
