apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stage
  labels:
    k8scomplex-cluster: stage
  namespace: k8scomplex
  annotations:
    strategy.spinnaker.io/max-version-history: '4'
    traffic.spinnaker.io/load-balancers: '["service stage"]'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8scomplex-cluster: stage
  template:
    metadata:
      labels:
        k8scomplex-cluster: stage
    spec:
      containers:
      - image: gcr.io/spinnaker-1022/k8scomplex:release
        name: k8scomplex-stage
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m

